version: '3.2'

services:
  academy-web:
    build:
      context: .
      dockerfile: front.dockerfile
    image: demo/front:web
    ports: 
      - "40:4200"
    container_name: academy_web
    volumes: 
      - ./data/nginx:/etc/nginx/conf.d/
    networks:
      - academynet


networks:
 academynet: